#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npx --no-install lint-staged
eslint --fix
npx --no-install jest --passWithNoTests --runInBand

# npx --no-install jest --passWithNoTests --runInBand

# npx --no-install eslint --fix && npx --no-install jest --passWithNoTests --runInBand